name: Update Data
on:
  schedule:
    - cron: "0 8 * * 1"  # Exécuter tous les lundis à 8h00 UTC
  workflow_dispatch:  # Permet le déclenchement manuel du workflow

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Version plus récente

      - name: Set up Python
        uses: actions/setup-python@v4  # Version plus récente
        with:
          python-version: '3.10'  # Version spécifique de Python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run update script
        run: python scripts/update_script.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Passage du token pour les API

      - name: Commit and push if changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update data $(date +'%Y-%m-%d')"
          git push
