name: Update Data
on:
  schedule:
    - cron: "0 8 * * 1"  # Exécuter tous les lundis à 8h00 UTC
  workflow_dispatch:  # Permettre le déclenchement manuel

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Explicitement demander les permissions d'écriture
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pandas

      - name: Create directories
        run: mkdir -p data

      - name: Run update script
        run: python scripts/update_script.py
        
      - name: Check for changes
        id: git-check
        run: |
          git status --porcelain
          echo "::set-output name=modified::$(if git status --porcelain | grep .; then echo true; else echo false; fi)"

      - name: Commit and push if changed
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add -A
          git commit -m "Auto-update data $(date +'%Y-%m-%d')"
          git push
